// ---Auto Generated by Only4Play ---
package com.only4play.system.domain.admin.repository;

import com.only4play.jpa.support.BaseRepository;
import com.only4play.system.domain.admin.AdminUserPlatform;
import java.lang.Long;

public interface AdminUserPlatformRepository extends BaseRepository<AdminUserPlatform, Long> {
}
